version: "3"
services:
  api:
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      rag:
        condition: service_healthy
      qdrant:
        condition: service_started
  rag:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rag
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:                                        
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 5s                                     
      timeout: 5s                                     
      retries: 5   

  qdrant:
    image: qdrant/qdrant
    ports:  
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_db:
  qdrant_data:
  